In [1]:
import numpy as np #импортирую библиотеку numpy

In [ ]:
data = [1,2,3,4,5] #создаю обычной py лист

In [ ]:
arr= np.array(data) #создаю из list массив numpy

In [ ]:
print(arr) #вывожу на экран элементы из массива
print(arr.shape) # вывожу количество элементов
print(arr.dtype) #тип
print(arr.ndim) #размерность - одномерный массив, поэтому 1

In [ ]:
arr2 = np.array([1 ,2 ,3 ,4 ,5]) #можем создать и таким образом
print(arr2)

In [ ]:
arr3 = np.array([1 ,2 ,3 ,4, 5], dtype=np.float)
print(arr3)
print(arr3.dtype)
print(len(arr3)) #можем посмотреть длину массива
print(arr.size)

In [ ]:
arr3 = arr3.astype(np.int64) # приводим все элементы float к типу int

print(arr3)
print(arr3.dtype)

In [ ]:
arr4 = np.arange(0, 20, 1.5) #генерирует лист от 0 до 20 с шагом в 1.5
print(arr4)

In [ ]:
arr5 = np.linspace(0, 2, 5) #числа 5 чисел от 0 до 2
print(arr5) #Если не понимаешь, поиграйся с последним значением

In [ ]:
random_arr = np.random.random((5,)) #генерируем список из 5 рандомных чисел
random_arr


In [ ]:
random_arr2 = np.random.random_sample((5,)) #работает таким же образом как и пример выше
random_arr2

In [ ]:
random_arr3 = (10 - 5) * np.random.random_sample((5,)) - 5 #генерация 5 рандомных чисел в диапазоне от 10 до -5
random_arr3

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

arr = np.sqrt(arr) #sqrt преобразует числа из массива в квадратные из этих чисел
print(arr)

arr = np.sin(arr) #sin - синус
print(arr)

arr = np.cos(arr) #cos - косинус
print(arr)

arr = np.log(arr) #log - логарифм
print(arr)

arr = np.exp(arr) #exp - экспонента
print(arr)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

print(a)
print(b)

In [ ]:
c = np.add(a,b) # c = a + b
print(c)

In [ ]:
a * b #np.multiply(a,b)

In [ ]:
a - b #np.subtract

In [ ]:
a / b #np.divide

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr * 2 #все элементы умножить на 2
print(arr)
arr = arr ** 2 #все элементы возводим в квадрат
print(arr)

In [ ]:
arr = np.random.randint(-5, 10, 10) # рандомные числа от - 5 до 10 в количестве 10
arr

In [ ]:
print(arr.max()) #поиск самого большого элемента в списке
print(arr.min()) #самого минимума
print(arr.mean()) #среднего
print(arr.sum()) #сумма
print(arr.std()) #стандартное отклонение
print(np.median(arr)) #медиана

In [ ]:
arr < 2 #массив меньше 2, проверяем каждый элемент массиван на соответствие условия

In [ ]:
np.insert(arr,2, -20)# вставляем элемент 20 в позицию 2(индекс в массиве)

In [ ]:
np.delete(arr, 2) #удаляем элемент во 2 позиции

In [ ]:
np.sort(arr) #сортировка 

In [ ]:
arr2 = np.array([0,0,0])
arr = np.concatenate((arr, arr2)) #склеивает 2 списка вместе
arr

In [ ]:
np.array_split(arr, 3)# делим наш список на 3 списка  #hsplit, vsplit 

In [ ]:
arr = np.array([1,-2,3,-4,5])
arr[0] = 0 #обнуляем первый элемент
print(arr[2]) #выводим 2 элемент(индекс)
print(arr[0:2]) #срез, смотрим элемент от 0 до 2(по индексу)
print(arr[::-1]) #переворачиваем массив в обратном порядке
print(arr[arr < 2]) # выбираем элементы из списка которые меньше 2
print(arr[(arr < 2) & (arr > 0)]) #меньше двух и больше нуля
print(arr[(arr > 4) | (arr < 0)]) #больше четырех ИЛИ меньше нуля
arr[1:4] = 0 #обнуляем все элементы с 1 по 4 
print(arr)

In [ ]:
matrix = np.array([(1,2,3),(4,5,6)],dtype = np.float64)
matrix

In [ ]:
matrix = np.array([(1,2,3),(4,5,6),(7,8,9)])
matrix

In [ ]:
a_3d_array = np.array([[1, 2],[3,4],[5,6],[7,8]]) #трехмерный массив
a_3d_array

In [ ]:
matrix = np.array([(1,2,3),(4,5,6),(7,8,9)])
matrix
print(matrix.shape) #возвращает количество строк кортеж. сколько строк и столбцов
print(matrix.ndim) #размерность 2 - двумерная
print(matrix.size) #количество элементов

In [ ]:
matrix.reshape(1 , 9) #где 1 это количество строк, а 9 столбцов, изменили матрицу


In [ ]:
matrix = np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
matrix

In [ ]:
matrix.reshape(2,6) #меняем на 2 строки и 6 столбцов. Обязательно точно подгонять количество,просто так из головы взять и написать не выйдет

In [ ]:
matrix2 = np.random.random((2,2)) #можно создавать двумерные массивы со случайными числами
matrix2

In [ ]:
print(matrix)
matrix = np.resize(matrix, (2, 2)) #пишем что мы хотим оставить, остальное удаляется
print()
print(matrix)

In [ ]:
new_matrix = np.arange(16).reshape(2,8)
new_matrix

In [ ]:
np.zeros((2,3)) #создаем матрицу из нулей указанной размерности

In [ ]:
np.ones((3,3)) #создает матрицу единиц указанной размерности

In [ ]:
np.eye(5) #создаем единичную матрицу указанного порядка

In [ ]:
np.full((3,3),9) #создает матрицу указанной размерности и заполненную указанным значением

In [ ]:
np.empty((3,2)) #пустая матрица указанного значения

In [ ]:
matrix.dot(matrix2) #скалярное произведение

In [ ]:
#Axis 0 - ось строк, axis 1 - ось столбцов

In [2]:
matrix = np.array([(1,2,3),(4,5,6),(7,8,9)])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.delete(matrix,1,axis=0) #удаляет 1 строку по  axis 0 - ось строк

array([[1, 2, 3],
       [7, 8, 9]])

In [4]:
np.delete(matrix,1,axis=1) #удаляет 1 строку по axis 1 - ось столбцов

array([[1, 3],
       [4, 6],
       [7, 9]])

In [6]:
matrix.sum()

45

In [7]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print(matrix.max())
print(matrix.max(axis=0)) #ищем максимальный элемент каждой строки


9
[3 6 9]


In [10]:
np.mean(matrix, axis = 0) #среднее значение идет по строкам(1 + 4 + 7)/3 = 4
#2 + 5 + 8/3 = 5
#3 + 6 + 9|3 = 6

array([4., 5., 6.])

In [11]:
np.mean(matrix, axis = 1) #среднее значение идет по столбцам
#1 + 2 + 3/3 = 2
#4+5+6/3 = 5
#7+8+9/3 = 8

array([2., 5., 8.])

In [13]:
matrix**2 #также работает возведение в квадрат

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [20]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print()
arr2 = np.array(([7,8,9],[10,11,12]))
print(arr2)
print()
arr = np.concatenate((arr1,arr2),axis = 1) #добавляем arr2 к arr 1 как столбцы
arr

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]



array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [23]:
arr = np.concatenate((arr1,arr2),axis = 0) #добавляем arr2 к arr1 как строки
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
np.hstack((arr1,arr2)) #тоже самое, но удобнее

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [26]:
np.vstack((arr1,arr2)) #аналогично

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
np.split(arr,2) #разбиваем на 2 матрицы

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [28]:
np.split(arr,2, axis = 0)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [31]:
np.split(arr,3,axis = 1)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [32]:
np.append(arr,np.array([1,2,3])) #можно добавлять с помощью append в конец строки

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3])

# Индексация

In [33]:
matrix = np.array([(1,2,3),(4,5,6),(7,8,9)])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
matrix[1,2] #2 элемент 1 строки

6

In [35]:
matrix[2] #2 строка

array([7, 8, 9])

In [36]:
matrix[:,2] #берем все строки и из всех строк отбираем элементы которые находятся во 2 столбце

array([3, 6, 9])

In [37]:
matrix[1:3,0:2] #берем все строки которые идут с 1 по 3(не включительно)
#и отбираем только 0 и 1 столбец, получаем прямоугольник снизу

array([[4, 5],
       [7, 8]])

In [38]:
matrix[matrix > 2 ] #получаем список всех элементов матрицы которые больше 2

array([3, 4, 5, 6, 7, 8, 9])

# Специальные операции

In [39]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
matrix.T #транспонировананя матрица у которой строки и строки меняются местами 

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
matrix.flatten() #в массив

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.linalg.inv(matrix) #обратная матрица

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [43]:
np.trace(matrix) #след матрицы

15

In [44]:
np.linalg.det(matrix) #определитель

-9.51619735392994e-16

In [45]:
 np.linalg.matrix_rank(matrix) #ранк матрицы

2

In [46]:
eigenvalues, eigenvectors = np.linalg.eig(matrix) #собственные числа и векторы
print(eigenvalues)
print()
print(eigenvectors)

[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [47]:
np.info(np.eye) #передаем нужную нам функцию и нам выводится документация

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

In [ ]:
np.loadtxt('file.txt') #загрузка из текстового файла
np.genfromtxt('file.csv') #загрузка из csv файла
np.savetxt('file.txt',arr,delimiter = ' ') #запись в текстовый файл
np.savetxt('file.csv',arr,delimiter = ',') #запись в csv файл