In [2]:
import numpy as np #импортирую библиотеку numpy

In [ ]:
data = [1,2,3,4,5] #создаю обычной py лист

In [ ]:
arr= np.array(data) #создаю из list массив numpy

In [ ]:
print(arr) #вывожу на экран элементы из массива
print(arr.shape) # вывожу количество элементов
print(arr.dtype) #тип
print(arr.ndim) #размерность - одномерный массив, поэтому 1

In [ ]:
arr2 = np.array([1 ,2 ,3 ,4 ,5]) #можем создать и таким образом
print(arr2)

In [ ]:
arr3 = np.array([1 ,2 ,3 ,4, 5], dtype=np.float)
print(arr3)
print(arr3.dtype)
print(len(arr3)) #можем посмотреть длину массива
print(arr.size)

In [ ]:
arr3 = arr3.astype(np.int64) # приводим все элементы float к типу int

print(arr3)
print(arr3.dtype)

In [ ]:
arr4 = np.arange(0, 20, 1.5) #генерирует лист от 0 до 20 с шагом в 1.5
print(arr4)

In [ ]:
arr5 = np.linspace(0, 2, 5) #числа 5 чисел от 0 до 2
print(arr5) #Если не понимаешь, поиграйся с последним значением

In [ ]:
random_arr = np.random.random((5,)) #генерируем список из 5 рандомных чисел
random_arr


In [ ]:
random_arr2 = np.random.random_sample((5,)) #работает таким же образом как и пример выше
random_arr2

In [ ]:
random_arr3 = (10 - 5) * np.random.random_sample((5,)) - 5 #генерация 5 рандомных чисел в диапазоне от 10 до -5
random_arr3

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

arr = np.sqrt(arr) #sqrt преобразует числа из массива в квадратные из этих чисел
print(arr)

arr = np.sin(arr) #sin - синус
print(arr)

arr = np.cos(arr) #cos - косинус
print(arr)

arr = np.log(arr) #log - логарифм
print(arr)

arr = np.exp(arr) #exp - экспонента
print(arr)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

print(a)
print(b)

In [ ]:
c = np.add(a,b) # c = a + b
print(c)

In [ ]:
a * b #np.multiply(a,b)

In [ ]:
a - b #np.subtract

In [ ]:
a / b #np.divide

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr * 2 #все элементы умножить на 2
print(arr)
arr = arr ** 2 #все элементы возводим в квадрат
print(arr)

In [3]:
arr = np.random.randint(-5, 10, 10) # рандомные числа от - 5 до 10 в количестве 10
arr

array([ 5, -5, -5,  1,  9,  2,  2, -1,  1, -4])

In [4]:
print(arr.max()) #поиск самого большого элемента в списке
print(arr.min()) #самого минимума
print(arr.mean()) #среднего
print(arr.sum()) #сумма
print(arr.std()) #стандартное отклонение
print(np.median(arr)) #медиана

9
-5
0.5
5
4.2485291572496005
1.0


In [7]:
arr < 2 #массив меньше 2, проверяем каждый элемент массиван на соответствие условия

array([False,  True,  True,  True, False, False, False,  True,  True,
        True])

In [8]:
np.insert(arr,2, -20)# вставляем элемент 20 в позицию 2(индекс в массиве)

array([  5,  -5, -20,  -5,   1,   9,   2,   2,  -1,   1,  -4])

In [9]:
np.delete(arr, 2) #удаляем элемент во 2 позиции

array([ 5, -5,  1,  9,  2,  2, -1,  1, -4])

In [11]:
np.sort(arr) #сортировка 

array([-5, -5, -4, -1,  1,  1,  2,  2,  5,  9])

In [12]:
arr2 = np.array([0,0,0])
arr = np.concatenate((arr, arr2)) #склеивает 2 списка вместе
arr

array([ 5, -5, -5,  1,  9,  2,  2, -1,  1, -4,  0,  0,  0])

In [13]:
np.array_split(arr, 3)# делим наш список на 3 списка  #hsplit, vsplit 

[array([ 5, -5, -5,  1,  9]), array([ 2,  2, -1,  1]), array([-4,  0,  0,  0])]

In [15]:
arr = np.array([1,-2,3,-4,5])
arr[0] = 0 #обнуляем первый элемент
print(arr[2]) #выводим 2 элемент(индекс)
print(arr[0:2]) #срез, смотрим элемент от 0 до 2(по индексу)
print(arr[::-1]) #переворачиваем массив в обратном порядке
print(arr[arr < 2]) # выбираем элементы из списка которые меньше 2
print(arr[(arr < 2) & (arr > 0)]) #меньше двух и больше нуля
print(arr[(arr > 4) | (arr < 0)]) #больше четырех ИЛИ меньше нуля
arr[1:4] = 0 #обнуляем все элементы с 1 по 4 
print(arr)

3
[ 0 -2]
[ 5 -4  3 -2  0]
[ 0 -2 -4]
[]
[-2 -4  5]
[0 0 0 0 5]


In [17]:
matrix = np.array([(1,2,3),(4,5,6)],dtype = np.float64)
matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
matrix = np.array([(1,2,3),(4,5,6),(7,8,9)])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a_3d_array = np.array([[1, 2],[3,4],[5,6],[7,8]]) #трехмерный массив
a_3d_array

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
matrix = np.array([(1,2,3),(4,5,6),(7,8,9)]
matrix

SyntaxError: invalid syntax (<ipython-input-21-23a56363fc6c>, line 2)